# Generated by Django 3.2.21 on 2023-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='lookup_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
